# Generated by Django 3.2.19 on 2024-06-28 14:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0013_auto_20240628_1418'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('bookmarks', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookmark',
            name='auction',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='bookmarked', to='auctions.auction'),
        ),
        migrations.AlterUniqueTogether(
            name='bookmark',
            unique_together={('owner', 'auction')},
        ),
        migrations.RemoveField(
            model_name='bookmark',
            name='auctions',
        ),
    ]
