# Generated by Django 3.2.19 on 2024-04-19 15:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Auctioneer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=6)),
                ('name', models.CharField(max_length=60)),
                ('email', models.CharField(max_length=60)),
                ('phone', models.CharField(max_length=12)),
                ('postcode', models.CharField(max_length=6)),
                ('street_address', models.CharField(max_length=40)),
                ('city', models.CharField(max_length=40)),
                ('description', models.TextField(blank=True)),
                ('image', models.ImageField(default='../default_profile_dwzcuabfl', upload_to='images/')),
                ('owner', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
