# Generated by Django 3.2.19 on 2024-05-04 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctioneers', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='auctioneer',
            name='title',
        ),
        migrations.AlterField(
            model_name='auctioneer',
            name='image',
            field=models.ImageField(default='../default_auctioneer_dwzcuabfl', upload_to='images/'),
        ),
    ]
