# Generated by Django 3.2.19 on 2024-06-18 16:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('auctioneers', '0002_auto_20240504_1045'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='auctioneer',
            name='image',
        ),
        migrations.AddField(
            model_name='auctioneer',
            name='auctioneer_image',
            field=models.FileField(blank=True, null=True, upload_to='auctioneer_image'),
        ),
        migrations.AlterField(
            model_name='auctioneer',
            name='owner',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='auctioneer', to=settings.AUTH_USER_MODEL),
        ),
    ]
