# Generated by Django 3.2.19 on 2024-07-01 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctioneers', '0006_alter_auctioneer_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auctioneer',
            name='image',
            field=models.ImageField(default='../default_auctioneer_dwzcuabfl', upload_to='images/'),
        ),
    ]
