# Generated by Django 3.2.19 on 2024-04-19 11:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Auctions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=20)),
                ('productcategory', models.CharField(choices=[('home', 'Home'), ('office', 'Office'), ('building', 'Building'), ('vehicle', 'Vehicle'), ('industry', 'Industry'), ('agriculture', 'Agriculture')], max_length=30)),
                ('bidder', models.CharField(choices=[('furniture', 'Furniture'), ('chair', 'Chair'), ('table', 'Table'), ('bicycle', 'Bicycle'), ('bed', 'Bed'), ('refrigerator', 'Refrigerator'), ('pc', 'Pc'), ('phones', 'Phones')], max_length=30)),
                ('autocategory', models.CharField(choices=[('car', 'Car'), ('minibus', 'Minibus'), ('truck', 'Truck'), ('bus', 'Bus'), ('escavator', 'Escavator'), ('motocycle', 'Motocycle')], max_length=30)),
                ('openingday', models.CharField(choices=[('monday', 'Monday'), ('tuesday', 'Tuesday'), ('wednesday', 'Wednesday'), ('thursday', 'Thursday')], default='monday', max_length=30)),
                ('description', models.TextField()),
                ('year', models.PositiveIntegerField()),
                ('price', models.FloatField()),
                ('image', models.ImageField(default='../default_post_dwzcuabfl', upload_to='images/')),
                ('fueltype', models.CharField(choices=[('petrol', 'Petrol'), ('hybrid', 'Hybrid'), ('diesel', 'Diesel'), ('electric', 'Electric')], default='petrol', max_length=32)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='auction', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
