# Generated by Django 3.2.19 on 2024-04-19 15:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='auctions',
            old_name='openingday',
            new_name='auctionstartday',
        ),
    ]
