# Generated by Django 3.2.19 on 2024-04-19 16:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0002_rename_openingday_auctions_auctionstartday'),
    ]

    operations = [
        migrations.RenameField(
            model_name='auctions',
            old_name='bidder',
            new_name='item_products',
        ),
    ]
