# Generated by Django 3.2.19 on 2024-04-19 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0003_rename_bidder_auctions_item_products'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auctions',
            name='autocategory',
            field=models.CharField(choices=[('car', 'Car'), ('minibus', 'Minibus'), ('truck', 'Truck'), ('bus', 'Bus'), ('escavator', 'Escavator'), ('motocycle', 'Motocycle')], default='0', max_length=30),
        ),
        migrations.AlterField(
            model_name='auctions',
            name='item_products',
            field=models.CharField(choices=[('furniture', 'Furniture'), ('chair', 'Chair'), ('table', 'Table'), ('bicycle', 'Bicycle'), ('bed', 'Bed'), ('refrigerator', 'Refrigerator'), ('pc', 'Pc'), ('phones', 'Phones')], default='0', max_length=30),
        ),
    ]
