# Generated by Django 3.2.19 on 2024-04-19 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0004_auto_20240419_1630'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auctions',
            name='autocategory',
            field=models.CharField(choices=[('car', 'Car'), ('minibus', 'Minibus'), ('truck', 'Truck'), ('bus', 'Bus'), ('escavator', 'Escavator'), ('motocycle', 'Motocycle'), ('other', 'Other')], default='0', max_length=30),
        ),
        migrations.AlterField(
            model_name='auctions',
            name='fueltype',
            field=models.CharField(choices=[('petrol', 'Petrol'), ('hybrid', 'Hybrid'), ('diesel', 'Diesel'), ('electric', 'Electric'), ('other', 'Other')], default='petrol', max_length=32),
        ),
        migrations.AlterField(
            model_name='auctions',
            name='item_products',
            field=models.CharField(choices=[('furniture', 'Furniture'), ('chair', 'Chair'), ('table', 'Table'), ('bicycle', 'Bicycle'), ('bed', 'Bed'), ('refrigerator', 'Refrigerator'), ('pc', 'Pc'), ('phones', 'Phones'), ('other', 'Other')], default='0', max_length=30),
        ),
    ]
