# Generated by Django 3.2.19 on 2024-05-02 15:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0005_auto_20240419_1647'),
    ]

    operations = [
        migrations.RenameField(
            model_name='auctions',
            old_name='auctionstartday',
            new_name='auctionday',
        ),
        migrations.RenameField(
            model_name='auctions',
            old_name='autocategory',
            new_name='auto',
        ),
        migrations.RenameField(
            model_name='auctions',
            old_name='item_products',
            new_name='items',
        ),
    ]
