# Generated by Django 3.2.19 on 2024-06-18 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0007_rename_productcategory_auctions_categories'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auctions',
            name='image',
            field=models.ImageField(default='default.webp', upload_to='images/'),
        ),
    ]
