# Generated by Django 3.2.19 on 2024-06-18 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0008_alter_auctions_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='auctions',
            name='image',
        ),
        migrations.AddField(
            model_name='auctions',
            name='auctioneer_image',
            field=models.FileField(blank=True, null=True, upload_to='auctioneer_image'),
        ),
    ]
