# Generated by Django 3.2.19 on 2024-06-20 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0010_auto_20240619_1735'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auctions',
            name='auto',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='auctions',
            name='categories',
            field=models.CharField(choices=[('home', 'Home'), ('office', 'Office'), ('building', 'Building'), ('vehicle', 'Vehicle'), ('industry', 'Industry'), ('agriculture', 'Agriculture')], default='vehicle', max_length=30),
        ),
        migrations.AlterField(
            model_name='auctions',
            name='image',
            field=models.ImageField(default='../default_auction_image', upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='auctions',
            name='items',
            field=models.CharField(choices=[('furniture', 'Furniture'), ('chair', 'Chair'), ('table', 'Table'), ('bicycle', 'Bicycle'), ('bed', 'Bed'), ('refrigerator', 'Refrigerator'), ('pc', 'Pc'), ('phones', 'Phones'), ('other', 'Other')], max_length=30, null=True),
        ),
    ]
