# Generated by Django 3.2.19 on 2024-06-28 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0012_auto_20240628_0001'),
    ]

    operations = [
        migrations.CreateModel(
            name='Auction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=20)),
                ('categories', models.CharField(choices=[('home', 'Home'), ('office', 'Office'), ('building', 'Building'), ('vehicle', 'Vehicle'), ('industry', 'Industry'), ('agriculture', 'Agriculture')], default='vehicle', max_length=30)),
                ('items', models.CharField(choices=[('furniture', 'Furniture'), ('chair', 'Chair'), ('table', 'Table'), ('bicycle', 'Bicycle'), ('bed', 'Bed'), ('refrigerator', 'Refrigerator'), ('pc', 'Pc'), ('phones', 'Phones'), ('other', 'Other')], default='phones', max_length=30)),
                ('auto', models.CharField(default='other', max_length=30)),
                ('auctionday', models.CharField(choices=[('monday', 'Monday'), ('tuesday', 'Tuesday'), ('wednesday', 'Wednesday'), ('thursday', 'Thursday')], default='monday', max_length=30)),
                ('description', models.TextField()),
                ('year', models.PositiveIntegerField()),
                ('price', models.FloatField()),
                ('image', models.ImageField(default='post_image', upload_to='images/')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.RemoveField(
            model_name='auctions',
            name='owner',
        ),
    ]
