# Generated by Django 3.2.19 on 2024-06-28 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0014_auto_20240628_1418'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='auction',
            name='auto',
        ),
        migrations.RemoveField(
            model_name='auction',
            name='items',
        ),
        migrations.AddField(
            model_name='auction',
            name='products',
            field=models.CharField(choices=[('furniture', 'Furniture'), ('chair', 'Chair'), ('table', 'Table'), ('bicycle', 'Bicycle'), ('bed', 'Bed'), ('refrigerator', 'Refrigerator'), ('pc', 'Pc'), ('phones', 'Phones'), ('car', 'Car'), ('minibus', 'Minibus'), ('truck', 'Truck'), ('bus', 'Bus'), ('escavator', 'Escavator'), ('motocycle', 'Motocycle'), ('other', 'Other')], default='phones', max_length=30),
        ),
        migrations.AlterField(
            model_name='auction',
            name='categories',
            field=models.CharField(choices=[('home', 'Home'), ('office', 'Office'), ('building', 'Building'), ('vehicle', 'Vehicle'), ('industry', 'Industry'), ('agriculture', 'Agriculture'), ('automobile', 'Automobile'), ('sports', 'Sports'), ('electronics', 'Electronics')], default='vehicle', max_length=30),
        ),
    ]
