# Generated by Django 3.2.19 on 2024-07-01 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0015_auto_20240628_1956'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auction',
            name='image',
            field=models.ImageField(default='auction_image', upload_to='images/'),
        ),
    ]
