# Generated by Django 3.2.19 on 2024-07-01 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0016_alter_auction_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auction',
            name='image',
            field=models.ImageField(default='../default_post_dwzcuabfl', upload_to='images/'),
        ),
    ]
