# Generated by Django 3.2.19 on 2024-07-03 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0017_alter_auction_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auction',
            name='categories',
            field=models.CharField(choices=[('home', 'Home'), ('office', 'Office'), ('building', 'Building'), ('vehicle', 'Vehicle'), ('industry', 'Industry'), ('agriculture', 'Agriculture'), ('automobile', 'Automobile'), ('sports', 'Sports'), ('electronics', 'Electronics')], default='home', max_length=30),
        ),
    ]
