# Generated by Django 3.2.19 on 2024-09-24 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0018_alter_auction_categories'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auction',
            name='image',
            field=models.ImageField(default='../default_auction_mvxwre', upload_to='images/'),
        ),
    ]
