# Generated by Django 3.2.19 on 2024-09-26 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0020_alter_auction_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auction',
            name='image',
            field=models.ImageField(blank=True, default='../default_post_mvxwre', upload_to='images/'),
        ),
    ]
